FROM gitlab/gitlab-ce

# SSH login fix. Otherwise user is kicked off after login
# https://docs.docker.com/engine/examples/running_ssh_service/
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
